services: 
  flask_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
      
  redis:
    image: redis:7.4.1
    command: ["redis-server", "--requirepass", "testeredis"] 
    ports:
      - "6379:6379"
      
